export 'package:soft_frontend/models/empleado.model.dart';
export 'package:soft_frontend/models/user.model.dart';
export 'package:soft_frontend/models/permiso.model.dart';
export 'package:soft_frontend/models/rol.model.dart';
export 'package:soft_frontend/models/rolPermiso.model.dart';
export 'package:soft_frontend/models/sesion.model.dart';
export 'package:soft_frontend/models/cliente.model.dart';
export 'package:soft_frontend/models/ventas.model.dart';
export 'package:soft_frontend/models/detalleventa.model.dart';
export 'package:soft_frontend/models/Arqueo.model.dart';
export 'package:soft_frontend/models/cliente.model.dart';
export 'package:soft_frontend/models/errorPeticion.model.dart';
export 'package:soft_frontend/models/facturaBuscada.model.dart';
export 'package:soft_frontend/models/manipularFacturaResponse.dart';
export 'package:soft_frontend/models/Tipoproducto.model.dart';
// export 'package:soft_frontend/models/Producto.model.dart';
